# Generated by Django 5.2.14 on 2026-06-21 15:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_lancamento_pagamento_trafego'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaoGeralPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_inicio', models.DateField(verbose_name='início do período')),
                ('data_fim', models.DateField(verbose_name='fim do período')),
                ('visitas', models.PositiveIntegerField(default=0, verbose_name='visitas')),
                ('visualizacoes_categoria', models.PositiveIntegerField(default=0, verbose_name='visualizações de categoria')),
                ('visualizacoes_produto', models.PositiveIntegerField(default=0, verbose_name='visualizações de produto')),
                ('carrinhos_criados', models.PositiveIntegerField(default=0, verbose_name='carrinhos criados')),
                ('checkout_iniciado', models.PositiveIntegerField(default=0, verbose_name='checkout iniciado')),
                ('checkout_entrega', models.PositiveIntegerField(default=0, verbose_name='etapa de entrega')),
                ('checkout_pagamento', models.PositiveIntegerField(default=0, verbose_name='etapa de pagamento')),
                ('pedidos_criados', models.PositiveIntegerField(default=0, verbose_name='pedidos criados')),
                ('pedidos_pagos', models.PositiveIntegerField(default=0, help_text='Pedidos pagos no período. Equivale ao total de vendas.', verbose_name='pedidos pagos')),
                ('receita', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='receita')),
                ('observacao', models.TextField(blank=True, default='', verbose_name='observação')),
            ],
            options={
                'verbose_name': 'período da visão geral',
                'verbose_name_plural': 'períodos da visão geral',
                'ordering': ['-data_inicio', '-id'],
                'indexes': [models.Index(fields=['data_inicio', 'data_fim'], name='finance_vis_data_in_6b6c96_idx')],
            },
        ),
    ]
