# Generated by Codex on 2026-05-29

from django.db import migrations


CATEGORY_TYPE_BY_SLUG = {
    "godaddy-email-profissional": "DESPESA",
    "godaddy-hospedagem": "DESPESA",
    "nuvemshop-nuvempago": "RECEITA",
    "nuvemshop-plano": "DESPESA",
    "salario-analista-ecommerce": "DESPESA",
}


def aplicar_tipos_por_categoria(apps, schema_editor):
    LancamentoFinanceiro = apps.get_model("finance", "LancamentoFinanceiro")

    for slug, tipo in CATEGORY_TYPE_BY_SLUG.items():
        LancamentoFinanceiro.objects.filter(categoria__slug=slug).update(tipo=tipo)


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_padroniza_categorias_financeiras"),
    ]

    operations = [
        migrations.RunPython(aplicar_tipos_por_categoria, migrations.RunPython.noop),
    ]
