# Generated by Django 5.2.14 on 2026-05-15 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('slug', models.SlugField(max_length=120, verbose_name='slug')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategorias', to='catalog.categoria', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'subcategoria',
                'verbose_name_plural': 'subcategorias',
                'ordering': ['categoria__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('nome_gestaoclick', models.CharField(help_text='Descrição usada no sistema GestãoClick.', max_length=255, verbose_name='nome (GestãoClick)')),
                ('nome_site', models.CharField(help_text='Descrição usada no site Nuvemshop.', max_length=255, verbose_name='nome (site)')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalog.marca', verbose_name='marca')),
                ('subcategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalog.subcategoria', verbose_name='subcategoria')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['nome_site'],
            },
        ),
        migrations.CreateModel(
            name='Variacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('sku_nuvemshop', models.CharField(max_length=50, unique=True, verbose_name='SKU Nuvemshop')),
                ('id_gestaoclick', models.CharField(blank=True, default='', max_length=50, verbose_name='ID GestãoClick')),
                ('codigo_barras', models.CharField(blank=True, default='', max_length=50, verbose_name='código de barras')),
                ('descricao', models.CharField(blank=True, default='', help_text='Ex: USB-C, Lightning, Preto, 128GB.', max_length=255, verbose_name='descrição da variação')),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='custo')),
                ('preco_loja', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço loja')),
                ('preco_site', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='preço site')),
                ('status_nuvemshop', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10, verbose_name='status Nuvemshop')),
                ('status_integracao', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10, verbose_name='status integração GestãoClick ↔ Nuvemshop')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='catalog.produto', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'variação',
                'verbose_name_plural': 'variações',
                'ordering': ['produto__nome_site', 'descricao'],
            },
        ),
        migrations.AddConstraint(
            model_name='subcategoria',
            constraint=models.UniqueConstraint(fields=('categoria', 'nome'), name='unique_subcategoria_nome_por_categoria'),
        ),
        migrations.AddConstraint(
            model_name='subcategoria',
            constraint=models.UniqueConstraint(fields=('categoria', 'slug'), name='unique_subcategoria_slug_por_categoria'),
        ),
    ]
