# Generated by Django 5.2.14 on 2026-05-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='sku_nuvemshop',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='SKU Nuvemshop'),
        ),
    ]
