# Generated by Django 5.2.14 on 2026-05-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_variacao_sku_nuvemshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacao',
            name='descricao',
            field=models.CharField(blank=True, default='', help_text='Ex: USB-C, Lightning, Preto, 128GB.', max_length=500, verbose_name='descrição da variação'),
        ),
    ]
