# Generated by Django 5.2.14 on 2026-05-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_variacao_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao_produto_gestaoclick',
            field=models.TextField(blank=True, default='', help_text='Descrição longa do produto no GestãoClick.', verbose_name='descrição do produto (GestãoClick)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao_produto_site',
            field=models.TextField(blank=True, default='', help_text='Descrição longa do produto no Nuvemshop.', verbose_name='descrição do produto (site)'),
        ),
    ]
