# Generated by Django 5.2.14 on 2026-05-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_produto_descricao_produto_gestaoclick_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['descricao_produto_site'], 'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
        migrations.AlterModelOptions(
            name='variacao',
            options={'ordering': ['produto__descricao_produto_site', 'descricao'], 'verbose_name': 'variação', 'verbose_name_plural': 'variações'},
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome_gestaoclick',
            field=models.CharField(blank=True, default='', help_text='Rótulo curto opcional para o produto no GestãoClick.', max_length=255, verbose_name='nome curto (GestãoClick)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome_site',
            field=models.CharField(blank=True, default='', help_text='Rótulo curto opcional para o produto no Nuvemshop.', max_length=255, verbose_name='nome curto (site)'),
        ),
    ]
