# Generated by Codex on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_produto_options_alter_variacao_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="variacao",
            name="preco_promocional",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="preço promocional",
            ),
        ),
    ]
