# Generated by Codex on 2026-05-29

from decimal import Decimal
import re
import unicodedata

from django.db import migrations


PROMOCOES = [
    (
        "CARREGADOR PORTÁTIL 10000mah C/DISPLAY WUP-1024 PEINING",
        None,
        Decimal("49.90"),
    ),
    ("FONTE APPLE BRANCO USB-C 20W", None, Decimal("139.90")),
    (
        "MÁQUINA DE CORTAR CABELO E BABEAR ELÉTRICA B-MAX C042",
        None,
        Decimal("29.90"),
    ),
    ("FONE DE OUVIDO EXTRA BASS PMCELL FO14", None, Decimal("9.90")),
    (
        "CABO USB IPHONE REFORÇADO PMCELL",
        "LIGHTNING DATA CABLE",
        Decimal("15.90"),
    ),
    (
        "CABO USB IPHONE REFORÇADO PMCELL",
        "TYPE C USB DATA CABLE",
        Decimal("15.90"),
    ),
    ("CABO USB IPHONE REFORÇADO PMCELL", "V8 DATA CABLE", Decimal("13.90")),
    (
        "CARREGADOR FONTE RÁPIDO INOVA C/2 ENTRADAS USB 3.1A 3160S",
        "BRANCO",
        Decimal("17.90"),
    ),
    (
        "CARREGADOR FONTE RÁPIDO INOVA C/2 ENTRADAS USB 3.1A 3160S",
        "PRETO",
        Decimal("17.90"),
    ),
    (
        "KIT CARREGADOR FLUXION CHARGE 33W TIPO C CRG233",
        "PRETO",
        Decimal("69.90"),
    ),
    (
        "KIT CARREGADOR FLUXION CHARGE 33W TIPO C CRG233",
        "BRANCO",
        Decimal("69.90"),
    ),
]


def normalizar(valor):
    texto = unicodedata.normalize("NFKD", valor or "")
    texto = "".join(c for c in texto if not unicodedata.combining(c))
    return re.sub(r"\s+", " ", texto.upper()).strip()


def texto_produto(variacao):
    produto = variacao.produto
    partes = [
        produto.descricao_produto_site,
        produto.descricao_produto_gestaoclick,
        produto.nome_site,
        produto.nome_gestaoclick,
    ]
    return normalizar(" ".join(partes))


def produto_confere(produto_normalizado, esperado):
    esperado_normalizado = normalizar(esperado)
    if esperado_normalizado in produto_normalizado:
        return True
    tokens = [t for t in re.split(r"[^A-Z0-9]+", esperado_normalizado) if len(t) > 2]
    return bool(tokens) and all(token in produto_normalizado for token in tokens)


def aplicar_precos_promocionais(apps, schema_editor):
    Variacao = apps.get_model("catalog", "Variacao")

    variacoes = list(Variacao.objects.select_related("produto"))
    total_por_produto = {}
    for variacao in variacoes:
        total_por_produto[variacao.produto_id] = (
            total_por_produto.get(variacao.produto_id, 0) + 1
        )

    for produto, variacao_esperada, preco in PROMOCOES:
        variacao_normalizada = normalizar(variacao_esperada)
        for variacao in variacoes:
            if not produto_confere(texto_produto(variacao), produto):
                continue

            descricao_variacao = normalizar(variacao.descricao)
            if variacao_esperada is None:
                if descricao_variacao and total_por_produto[variacao.produto_id] > 1:
                    continue
            elif variacao_normalizada not in descricao_variacao:
                continue

            variacao.preco_promocional = preco
            variacao.save(update_fields=["preco_promocional"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_variacao_preco_promocional"),
    ]

    operations = [
        migrations.RunPython(aplicar_precos_promocionais, migrations.RunPython.noop),
    ]
