# Generated by Codex on 2026-05-29

from decimal import Decimal

from django.db import migrations


AJUSTES = [
    (
        "CABO USB IPHONE REFORÇADO PMCELL",
        "LIGHTNING USB DATA CABLE",
        Decimal("15.90"),
    ),
    (
        "CABO USB IPHONE REFORÇADO PMCELL",
        "MICRO USB DATA CABLE",
        Decimal("13.90"),
    ),
    (
        "KIT CARREGADOR FLUXION CHARGE 33W TIPO C CRG233",
        "CINZA",
        Decimal("69.90"),
    ),
]


def aplicar_aliases(apps, schema_editor):
    Variacao = apps.get_model("catalog", "Variacao")

    for produto, variacao, preco in AJUSTES:
        Variacao.objects.filter(
            produto__descricao_produto_site__iexact=produto,
            descricao__iexact=variacao,
        ).update(preco_promocional=preco)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_preco_promocional_produtos_imagem"),
    ]

    operations = [
        migrations.RunPython(aplicar_aliases, migrations.RunPython.noop),
    ]
