# Generated by Codex on 2026-05-29

from decimal import Decimal
import re
import unicodedata

from django.db import migrations


PRECOS = [
    ("FONE DE OUVIDO TWS BLUETOOTH GET BUDS LITE", None, "139.90", "189.00"),
    ("FONE DE OUVIDO TWS BLUETOOTH GET SMART BUDS", None, "219.90", "289.00"),
    (
        "CAIXA DE SOM BLUETOOTH TWS GET POP LITE 40W RMS",
        None,
        "239.90",
        "299.00",
    ),
    ("FONE OUVIDO HEADPHONE BLUETOOTH GET ZEN", None, "199.00", "229.00"),
    (
        "CARREGADOR KIMASTER T110cc USB-C TURBO PD+QC 3.0",
        None,
        "62.90",
        "99.00",
    ),
    (
        "SUPORTE FIXO UNIVERSAL P/ TV 10 A 100 POLEGADAS ELG UNI80B",
        None,
        "14.90",
        "24.90",
    ),
    ("CABO HDMI 2.0v 3D READY 4K DE 1,8m - HS1018", None, "25.90", "39.00"),
    ("FONE DE OUVIDO USB-C C/FIO SKAIKY", "LIGHTNING", "59.90", "69.90"),
    ("FONE DE OUVIDO USB-C C/FIO SKAIKY", "USB-C", "69.90", "79.90"),
    ("SUPORTE PARA CELULAR SKAIKY", None, "24.90", "35.00"),
    (
        "CARREGADOR PORTÁTIL POWER BANK HREBOS FORZA 5000mah 65w",
        None,
        "379.90",
        "399.00",
    ),
    (
        "GIMBAL FOTOGRÁFICO RECONHECIMENTO FACIAL HREBOS PREMIUM",
        None,
        "197.90",
        "199.00",
    ),
    ("CABO CÉOS LINK 3 METROS CB-479 HREBOS PREMIUM", "USB-C", "69.00", "79.00"),
    (
        "CABO CÉOS LINK 3 METROS CB-479 HREBOS PREMIUM",
        "LIGHTNING",
        "59.00",
        "69.00",
    ),
    ("CABO CÉOS LINK 3 METROS CB-478 HREBOS PREMIUM", "USB-C", "79.90", "89.00"),
    (
        "CABO CÉOS LINK 3 METROS CB-478 HREBOS PREMIUM",
        "LIGHTNING",
        "69.90",
        "79.00",
    ),
    ("CABO SKIPPER CB-485 VOLT 1 METRO HREBOS", "USB-C", "89.00", "99.00"),
    (
        "CABO SKIPPER CB-485 VOLT 1 METRO HREBOS",
        "LIGHTNING",
        "79.00",
        "89.00",
    ),
    (
        "MICROFONE COM TRANSMISSOR CLIPMIC IF 1002 HREBOS",
        "USB-C",
        "179.90",
        "199.00",
    ),
    (
        "MICROFONE COM TRANSMISSOR CLIPMIC IF 1002 HREBOS",
        "LIGHTNING",
        "179.90",
        "199.00",
    ),
]


def normalizar(valor):
    texto = unicodedata.normalize("NFKD", valor or "")
    texto = "".join(c for c in texto if not unicodedata.combining(c))
    return re.sub(r"\s+", " ", texto.upper()).strip()


def texto_produto(variacao):
    produto = variacao.produto
    partes = [
        produto.descricao_produto_site,
        produto.descricao_produto_gestaoclick,
        produto.nome_site,
        produto.nome_gestaoclick,
    ]
    return normalizar(" ".join(partes))


def produto_confere(produto_normalizado, esperado):
    esperado_normalizado = normalizar(esperado)
    if esperado_normalizado in produto_normalizado:
        return True
    tokens = [t for t in re.split(r"[^A-Z0-9]+", esperado_normalizado) if len(t) > 2]
    return bool(tokens) and all(token in produto_normalizado for token in tokens)


def variacao_confere(descricao_normalizada, esperado):
    if esperado is None:
        return not descricao_normalizada or descricao_normalizada in {"-", "PADRAO"}

    esperado_normalizado = normalizar(esperado)
    if esperado_normalizado == "USB-C":
        return descricao_normalizada in {"USB-C", "USBC", "TYPE C", "TYPE-C"}
    return esperado_normalizado in descricao_normalizada


def aplicar_precos(apps, schema_editor):
    Variacao = apps.get_model("catalog", "Variacao")

    variacoes = list(Variacao.objects.select_related("produto"))
    for produto, variacao_esperada, preco_site, preco_loja in PRECOS:
        for variacao in variacoes:
            if not produto_confere(texto_produto(variacao), produto):
                continue
            if not variacao_confere(normalizar(variacao.descricao), variacao_esperada):
                continue

            variacao.preco_site = Decimal(preco_site)
            variacao.preco_loja = Decimal(preco_loja)
            variacao.save(update_fields=["preco_site", "preco_loja"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_preco_promocional_aliases_imagem"),
    ]

    operations = [
        migrations.RunPython(aplicar_precos, migrations.RunPython.noop),
    ]
