# Generated by Codex on 2026-05-29

from decimal import Decimal

from django.db import migrations


def aplicar_alias_power_bank(apps, schema_editor):
    Variacao = apps.get_model("catalog", "Variacao")
    Variacao.objects.filter(
        produto__descricao_produto_site__iexact=(
            "CARREGADOR PORTÁTIL POWER BANK HREBOS FORZA 50000mah 65w"
        ),
        descricao="",
    ).update(preco_site=Decimal("379.90"), preco_loja=Decimal("399.00"))


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_precos_produtos_novos_imagem"),
    ]

    operations = [
        migrations.RunPython(aplicar_alias_power_bank, migrations.RunPython.noop),
    ]
